# Generated by Django 3.2.13 on 2022-06-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('population_app', '0002_auto_20220605_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staties', to='population_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('age_group', models.CharField(choices=[('old', 'Old'), ('young', 'Young'), ('child', 'Child')], max_length=10)),
                ('population', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='population_app.city')),
            ],
        ),
    ]
